// Legacy data file - keeping for backward compatibility during migration
// TODO: Remove this file once all components are migrated to Supabase

export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number;
  colorway: string;
  image: string;
  category: string;
  gender: 'men' | 'women' | 'unisex';
  isNew?: boolean;
  isSale?: boolean;
  rating?: number;
  description?: string;
  tags?: string[];
}

// Keep existing products array for components that haven't been migrated yet
// This will be gradually removed as we migrate each component

export const products: Product[] = [
  {
    id: "1",
    name: "Adidas adizero adios pro 4",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Cloud White / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17814/ADI17814_400_1.jpg",
    //https://cdn.sportsshoes.com/product/A/ADI17711/ADI17711_400_1.jpg
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "2",
    name: "Adidas adizero adios pro 4",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Cloud White / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17818/ADI17818_400_1.jpg",
    //https://cdn.sportsshoes.com/product/A/ADI17711/ADI17711_400_1.jpg
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "3",
    name: "Adidas adizero adios pro 4",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Cloud White / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17712/ADI17712_400_1.jpg",
    //https://cdn.sportsshoes.com/product/A/ADI17711/ADI17711_400_1.jpg
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "4",
    name: "Adizero Adios Pro 4 Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Cloud White / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17812/ADI17812_400_1.jpg",
    //https://cdn.sportsshoes.com/product/A/ADI17711/ADI17711_400_1.jpg
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "5",
    name: "Adidas adizero adios pro 4",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Cloud White / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17710/ADI17710_400_1.jpg",
    //https://cdn.sportsshoes.com/product/A/ADI17711/ADI17711_400_1.jpg
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "6",
    name: "Adizero Adios Pro 4 Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Cloud White / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17810/ADI17810_400_1.jpg",
    //https://cdn.sportsshoes.com/product/A/ADI17711/ADI17711_400_1.jpg
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "7",
    name: "Adidas adizero adios pro 4",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Cloud White / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17713/ADI17713_400_1.jpg",
    //https://cdn.sportsshoes.com/product/A/ADI17711/ADI17711_400_1.jpg
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "8",
    name: "Adizero Adios Pro 4 Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17791/ADI17791_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "9",
    name: "Adizero Adios Pro 4",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17705/ADI17705_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "10",
    name: "Adizero Adios Pro 4",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17700/ADI17700_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "11",
    name: "Adizero Adios Pro 4",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17517/ADI17517_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "12",
    name: "Adizero Adios Pro 4 Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17532/ADI17532_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "13",
    name: "Adizero Adios Pro Evo 1",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17070/ADI17070_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "14",
    name: "Terrex Aggravic 3 Women's Trail Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17595/ADI17595_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "15",
    name: "Terrex Aggravic Speed Trail Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17573/ADI17573_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "16",
    name: "Terrex Aggravic Speed Trail Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17574/ADI17574_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "17",
    name: "Duramo Sl 2",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17645/ADI17645_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "18",
    name: "Galaxy 7 Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17660/ADI17660_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "19",
    name: "RunFalcon 5 Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17659/ADI17659_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "20",
    name: "Adizero Boston 12",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17642/ADI17642_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "21",
    name: "Supernova Ease Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17662/ADI17662_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "22",
    name: "Adizero Adios 9 Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17655/ADI17655_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "23",
    name: "Terrex Aggravic Speed Trail Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17570/ADI17570_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "24",
    name: "Adistar Byd Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17653/ADI17653_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "25",
    name: "Supernova Prima Women's Running Shoes",
    brand: "Adidas",
    price: 220,
    originalPrice: 220,
    colorway: "Red Whine / Core Black",
    image: "https://cdn.sportsshoes.com/product/A/ADI17658/ADI17658_400_1.jpg",
    category: "running",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.8,
    description: "The Ultraboost 21 is designed to give you incredible energy return when you need it most. The responsive cushioning helps keep your stride smooth and your run comfortable.",
    tags: ["cushioned", "responsive", "road-running"]
  },
  {
    id: "3",
    name: "Pegasus 38",
    brand: "Nike",
    price: 120,
    colorway: "Black / White / Volt",
    image: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/7e5bbb8c-a97b-4aea-9c23-cc7f6fb21e70/pegasus-38-road-running-shoes-1VHfGW.png",
    category: "running",
    gender: "men",
    isNew: true,
    isSale: false,
    rating: 4.5,
    description: "The Nike Pegasus 38 continues to put a spring in your step with the same responsive cushioning that let it earn its reputation as a runner's staple.",
    tags: ["cushioned", "versatile", "daily-trainer"]
  },
  {
    id: "4",
    name: "Fresh Foam 1080v11",
    brand: "New Balance",
    price: 150,
    colorway: "Blue / White",
    image: "https://nb.scene7.com/is/image/NB/m1080s11_nb_02_i?$pdpflexf2$&wid=440&hei=440",
    category: "running",
    gender: "men",
    isNew: true,
    isSale: false,
    rating: 4.6,
    description: "The Fresh Foam 1080v11 provides luxurious comfort for the long run. The plush Fresh Foam midsole delivers a soft, smooth ride.",
    tags: ["cushioned", "long-distance", "comfort"]
  },
  {
    id: "4",
    name: "Gel-Kayano 28",
    brand: "Asics",
    price: 160,
    colorway: "Black / Graphite Grey",
    image: "https://images.asics.com/is/image/asics/1011B189_003_SR_RT_GLB?$sfcc-product$",
    category: "stability",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.7,
    description: "The GEL-KAYANO 28 shoe is a stability running shoe that offers excellent support and comfort for overpronators.",
    tags: ["stability", "support", "overpronation"]
  },
  {
    id: "5",
    name: "Endorphin Speed 2",
    brand: "Saucony",
    price: 160,
    colorway: "Reverie / Lime",
    image: "https://www.saucony.com/dw/image/v2/AAKD_PRD/on/demandware.static/-/Sites-saucony_us-Library/default/dwd2c699fb/content/seasonal-content/homepage/2021/04/endorphin-speed-2-test-tile-d.jpg",
    category: "performance",
    gender: "unisex",
    isNew: true,
    isSale: false,
    rating: 4.9,
    description: "The Endorphin Speed 2 gives you the edge you want with the fit and feel you need. Perfect for race day or everyday speed training.",
    tags: ["speed", "racing", "tempo"]
  },
  {
    id: "6",
    name: "React Infinity Run FK 2",
    brand: "Nike",
    price: 140,
    originalPrice: 160,
    colorway: "White / Bright Crimson",
    image: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/78e75des9psqj7evlbzt/react-infinity-run-flyknit-2-road-running-shoes-5kKcpx.png",
    category: "cushioned",
    gender: "women",
    isNew: false,
    isSale: true,
    rating: 4.3,
    description: "The Nike React Infinity Run Flyknit 2 continues to help keep you running with improved comfort and a more responsive ride.",
    tags: ["cushioned", "stability", "road-running"]
  },
  {
    id: "7",
    name: "Cloudflow",
    brand: "On",
    price: 140,
    colorway: "Rock / Rose",
    image: "https://cdn.shopify.com/s/files/1/0601/6024/0305/files/3099967_1A.jpg?v=1691082071",
    category: "lightweight",
    gender: "women",
    isNew: false,
    isSale: false,
    rating: 4.4,
    description: "The Cloudflow is a lightweight, responsive running shoe designed for speed training, racing, and tempo running.",
    tags: ["lightweight", "responsive", "road-racing"]
  },
  {
    id: "8",
    name: "Clifton 8",
    brand: "Hoka",
    price: 130,
    colorway: "Blue / Coral",
    image: "https://cdn.shopify.com/s/files/1/0604/5170/9740/products/HOKAS-CLIFTON-8_1_1800x1800.webp?v=1651686834",
    category: "cushioned",
    gender: "women",
    isNew: true,
    isSale: false,
    rating: 4.6,
    description: "The Clifton 8 delivers a smooth, balanced ride with a soft, more responsive midsole and a supportive upper.",
    tags: ["cushioned", "lightweight", "daily-trainer"]
  },
  {
    id: "9",
    name: "Triumph 19",
    brand: "Saucony",
    price: 150,
    originalPrice: 170,
    colorway: "Alloy / Fire",
    image: "https://s7d4.scene7.com/is/image/WolverineWorldWide/S20678-20_1?wid=826&hei=685&resMode=bilin&op_usm=0.5,1.0,8,0&iccEmbed=0&printRes=72",
    category: "cushioned",
    gender: "men",
    isNew: false,
    isSale: true,
    rating: 4.5,
    description: "The Triumph 19 is all about comfort with PWRRUN+ cushioning that delivers a plush and responsive ride.",
    tags: ["cushioned", "comfort", "daily-trainer"]
  },
  {
    id: "10",
    name: "Ghost 14",
    brand: "Brooks",
    price: 130,
    colorway: "Black / Pearl / Mint",
    image: "https://www.brooksrunning.com/dw/image/v2/BGPF_PRD/on/demandware.static/-/Sites-brooks-master-catalog/default/dwd1c5feb7/original/120356/120356-467-l-ghost-14-womens-cushion-running-shoe.jpg",
    category: "neutral",
    gender: "women",
    isNew: true,
    isSale: false,
    rating: 4.7,
    description: "The Ghost 14 offers smooth transitions plus soft cushioning so your run feels easy, no matter the distance.",
    tags: ["neutral", "soft", "balanced"]
  },
  {
    id: "11",
    name: "Adrenaline GTS 22",
    brand: "Brooks",
    price: 130,
    colorway: "Black / Blue / Orange",
    image: "https://www.brooksrunning.com/dw/image/v2/BGPF_PRD/on/demandware.static/-/Sites-brooks-master-catalog/default/dw1ce11f2b/original/110357/110357-049-l-adrenaline-gts-22-mens-supportive-running-shoe.jpg",
    category: "stability",
    gender: "men",
    isNew: true,
    isSale: false,
    rating: 4.6,
    description: "The Adrenaline GTS 22 is a supportive running shoe that offers a perfect blend of cushioning and stability.",
    tags: ["stability", "support", "daily-trainer"]
  },
  {
    id: "12",
    name: "Wave Rider 25",
    brand: "Mizuno",
    price: 135,
    colorway: "Blue / Silver",
    image: "https://mizunoshop.net/files/pim_2345/pim/J1GC2103-03.jpg",
    category: "neutral",
    gender: "men",
    isNew: false,
    isSale: false,
    rating: 4.4,
    description: "The Wave Rider 25 is a neutral running shoe that offers a responsive ride with Mizuno Wave plate technology.",
    tags: ["neutral", "responsive", "daily-trainer"]
  }
];

// Filter products by various criteria
export const getNewArrivals = () => products.filter(product => product.isNew);
export const getSaleItems = () => products.filter(product => product.isSale);
export const getMensProducts = () => products.filter(product => product.gender === 'men' || product.gender === 'unisex');
export const getWomensProducts = () => products.filter(product => product.gender === 'women' || product.gender === 'unisex');

// Get unique brands
export const getBrands = () => {
  const brands = products.map(product => product.brand);
  return [...new Set(brands)];
};

// Get products by brand
export const getProductsByBrand = (brand: string) =>
    products.filter(product => product.brand.toLowerCase() === brand.toLowerCase());